apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-16T13:49:11Z"
  labels:
    app: gitops-devops-platform-deployment
  name: gitops-devops-platform-service
  namespace: default
  resourceVersion: "9732"
  uid: e061d598-c453-4e4d-8ffc-3e4ec5c63092
spec:
  clusterIP: 10.96.9.249
  clusterIPs:
  - 10.96.9.249
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: gitops-devops-platform-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
