apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: gitops-devops-platform-deployment
  name: gitops-devops-platform-service
  namespace: default
  
spec:
 
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: gitops-devops-platform-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
